spring:
  cloud:
    gateway:
      routes:
        - id: parse-api
          uri: lb://parse-api
          predicates:
            - Path=/parse-api/**
        - id: money-flow-api
          uri: lb://money-flow-api
          predicates:
            - Path=/money-flow-api/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  flyway:
    locations: classpath:migration/commons, classpath:migration/trigger
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=gateway
    username: gateway
    password: gateway
    pool:
      initial-size: 10
      max-size: 20
      validation-query: SELECT 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: "true"
    fetchRegistry: "true"
  instance:
    preferIpAddress: true