spring:
  application:
    name: money-flow-api
  flyway:
    enabled: true
    baseline-description: "Initial version"
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
